# How many maces are allowed to be crafted
mace-limit: 2
# causing crafted maces to glow when dropped
glowing-mace: true
# removes all maces that haven't been crafted
enforce-mace-limit: true
# allow maces to be stashed inside containers
stash-mace: false
# make maces immune to everything (fire, despawning...etc.) except for the Minecraft void
undestructable-maces: true


enchantments-limits:
  enchantable: true
  density : 3
  breach : 2
  unbreaking : 1
  mending : 0
  fire-aspect : 2
  wind-burst : 2
  vanishing-curse : 0

cooldown:
  enabled: true
  time: 1200 # in ticks (60 seconds * 20 tickPerRate = 1200 ticks)
  punish-missing: false

mace-craft-event:
  enabled: true
  time: 1200